import type { DocumentConfig } from './index'

function stripSpans(text: string): string {
  return text.replace(/<span[^>]*>/g, '').replace(/<\/span>/g, '')
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '[Not specified]'
  return new Date(dateStr + 'T00:00:00').toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
}

function buildCoverPage(data: Record<string, string>): string {
  const hasTraining = data.trainingData || data.trainingPurposes

  return `# AI Addendum

## Cover Page

| Field | Value |
|:---|:---|
| **Effective Date** | ${formatDate(data.effectiveDate)} |
| **Parent Agreement** | ${data.parentAgreement || '[Not specified]'} |
${hasTraining ? `| **Training Data** | ${data.trainingData || '[Not specified]'} |
| **Training Purposes** | ${data.trainingPurposes || '[Not specified]'} |
| **Training Restrictions** | ${data.trainingRestrictions || '[None]'} |
| **Improvement Restrictions** | ${data.improvementRestrictions || '[None]'} |` : `| **Model Training** | Provider may NOT use Customer data to train any Model (no training fields specified) |`}

---

*By signing below, the parties agree to this AI Addendum.*

| | **PROVIDER** | **CUSTOMER** |
|:---|:---|:---|
| **Print Name** | ${data.party1Name || '_________________'} | ${data.party2Name || '_________________'} |
| **Company** | ${data.party1Company || '_________________'} | ${data.party2Company || '_________________'} |
| **Date** | ${formatDate(data.effectiveDate)} | ${formatDate(data.effectiveDate)} |
| **Signature** | | |
`
}

const STANDARD_TERMS = stripSpans(`# AI Addendum — Standard Terms

1. AI Services

    1. Using AI Services. The AI Services are part of the Product and subject to the Agreement as supplemented by this AI Addendum. Customer may use AI Services by providing Input. The AI Services may generate Output in response to Input.

    2. Restrictions. Without limiting the restrictions contained in the Agreement, Customer will not: (a) use the AI Services for decision-making in a regulated industry or capacity without proper human oversight; (b) use the AI Services to violate or infringe the intellectual property or other proprietary rights of others; or (c) falsely state Output was created by a human.

    3. Model Training. Unless the Cover Page identifies Training Data and Training Purposes, Provider may not use Customer's Inputs or Outputs to Train any Model. If the Cover Page permits Training, then subject to the Training Restrictions, Provider may copy, modify, distribute, and use Training Data for the Training Purposes.

    4. Non-Training Improvement. Subject to the Improvement Restrictions, Provider may use Input, Output, and Training Data to provide, maintain, develop, and improve the AI System, provided that such usage does not constitute Training except to the extent authorized for Training Purposes.

2. Intellectual Property and Privacy

    1. Ownership. As between the parties, Customer retains all right, title, and interest in and to all Input, and owns all Output. To the extent permitted by Applicable Laws, Provider hereby assigns to Customer all right, title, and interest in and to Output.

    2. Personal Data. Nothing in this AI Addendum will reduce or limit Provider's obligations under Applicable Data Protection Laws regarding Personal Data that may be contained in Input.

    3. Rights to Input. Customer represents and warrants that it, all Users, and anyone submitting Input each have and will continue to have all rights necessary to submit Input to the AI Services.

3. Disclaimers

    1. Nature of AI. Due to the nature of artificial intelligence and machine learning, information generated by the AI Services may be incorrect or inaccurate. The AI Services are not human and are not a substitute for human oversight.

    2. Similarity of Output. Output may resemble or be duplicative of data, information, and materials created by the AI Services for others. Provider does not provide any representation or warranty that Output will not incorporate or reflect the data or materials of others.

*Common Paper AI Addendum Standard Terms Version 1.0 free to use under CC BY 4.0.*
`)

export function buildAiAddendumPreviewMarkdown(data: Record<string, string>): string {
  return buildCoverPage(data) + '\n\n---\n\n' + STANDARD_TERMS
}

export const aiAddendumConfig: DocumentConfig = {
  slug: 'ai-addendum',
  name: 'AI Addendum',
  description: 'An addendum addressing AI-specific terms including data use for model training, output disclaimers, and AI governance obligations.',
  filename: 'AI-Addendum.md',
  defaultData: {
    effectiveDate: new Date().toISOString().split('T')[0],
    party1Name: '', party1Company: '',
    party2Name: '', party2Company: '',
    trainingData: '',
    trainingPurposes: '',
    trainingRestrictions: '',
    improvementRestrictions: '',
    parentAgreement: '',
  },
  buildPreviewMarkdown: buildAiAddendumPreviewMarkdown,
}
